---
title: "computational_reproducibilitye"
format: html
editor: visual
---

# Computational Reproducibility

Original code listed many more libraries, but did not use them.

```{r setup}
requireNamespace("stargazer")
requireNamespace("lfe")
```

Extracted from Table5...R file. Modfied to reference functions through namespace, rather than load all libraries, and to reference data through path, rather than to change wd.

```{r}


data.dir <- "authors_replication/HuD_Replication/Final Data Sets/"

## Housing Search  ######################################################################################################

#Preamble

# Unless Otherwise Specified, Model Sequence is as follows:
# Model 1: treatment effect conditional on advertisement price
# Model 2: treatment effect also conditional on level of treatment outcome in advertised listing
# Model 3: treatment effect also conditional on racial composition of block group of advertised listing
# Model 4: treatment effect also conditional on racial composition of block group of recommended listing
# Model 5: treatment effect also conditional on price of recommended home

# Load data  

recs_trial_final <- readRDS(file.path(data.dir,"adsprocessed_JPE.rds"))

#construct separate indicators for market and control

recs_trial_final$market <- as.factor(sapply(strsplit(as.character(recs_trial_final$CONTROL), "-"), `[`, 1))
recs_trial_final$CONTROL <- as.factor(recs_trial_final$CONTROL)

recs_trial_final$show <- recs_trial_final$STOTUNIT
recs_trial_final$show[recs_trial_final$STOTUNIT<0] <- NA

#construct indicators for race groups
recs_trial_final$ofcolor <- 0
recs_trial_final$ofcolor[recs_trial_final$APRACE==2] <- 1
recs_trial_final$ofcolor[recs_trial_final$APRACE==3] <- 1
recs_trial_final$ofcolor[recs_trial_final$APRACE==4] <- 1
recs_trial_final$ofcolor <- as.factor(recs_trial_final$ofcolor)

recs_trial_final$count=1


# Dicrimination and Showings
# STEERING AND white NEIGHBORHOOD 

SHOW1 <- lfe::felm(show ~ ofcolor | CONTROL + SEQUENCE.x + month + HCITY + market + ARELATE2 + HHMTYPE + SAPPTAM + TSEX.x + THHEGAI + TPEGAI + THIGHEDU + TCURTENR +  ALGNCUR + AELNG1 + DPMTEXP + AMOVERS + age + ALEASETP + ACAROWN| 0 | CONTROL, data  = recs_trial_final)
SHOW3 <- lfe:: felm(show ~ ofcolor + w2012pc_Ad + b2012pc_Ad + a2012pc_Ad + hisp2012pc_Ad + logAdPrice | CONTROL + SEQUENCE.x + month + HCITY + market + ARELATE2 + HHMTYPE + SAPPTAM + TSEX.x + THHEGAI + TPEGAI + THIGHEDU + TCURTENR +  ALGNCUR + AELNG1 + DPMTEXP + AMOVERS + age + ALEASETP + ACAROWN| 0 |CONTROL, data  = recs_trial_final)

SHOW1_ <- lfe::felm(show ~ APRACE | CONTROL + SEQUENCE.x + month + HCITY + market + ARELATE2 + HHMTYPE + SAPPTAM + TSEX.x + THHEGAI + TPEGAI + THIGHEDU + TCURTENR +  ALGNCUR + AELNG1 + DPMTEXP + AMOVERS + age + ALEASETP + ACAROWN| 0 | CONTROL, data  = recs_trial_final)
SHOW3_ <- lfe::felm(show ~ APRACE + w2012pc_Ad + b2012pc_Ad + a2012pc_Ad + hisp2012pc_Ad + logAdPrice | CONTROL + SEQUENCE.x + month + HCITY + market + ARELATE2 + HHMTYPE + SAPPTAM + TSEX.x + THHEGAI + TPEGAI + THIGHEDU + TCURTENR +  ALGNCUR + AELNG1 + DPMTEXP + AMOVERS + age + ALEASETP + ACAROWN| 0 |CONTROL, data  = recs_trial_final)


##########################################################################################################################################################################

# STEERING 

recs_trial_final$home_av <- recs_trial_final$SAVLBAD
recs_trial_final$home_av[recs_trial_final$home_av<0] <- NA
recs_trial_final$home_av[recs_trial_final$home_av>1] <- 0

SHOWad1 <- lfe::felm(home_av ~ ofcolor | CONTROL + SEQUENCE.x + month + HCITY + market + ARELATE2 + HHMTYPE + SAPPTAM + TSEX.x + THHEGAI + TPEGAI + THIGHEDU + TCURTENR +  ALGNCUR + AELNG1 + DPMTEXP + AMOVERS + age + ALEASETP + ACAROWN| 0 | CONTROL, data  = recs_trial_final)
SHOWad3 <- lfe::felm(home_av ~ ofcolor + w2012pc_Ad + b2012pc_Ad + a2012pc_Ad + hisp2012pc_Ad + logAdPrice | CONTROL + SEQUENCE.x + month + HCITY + market + ARELATE2 + HHMTYPE + SAPPTAM + TSEX.x + THHEGAI + TPEGAI + THIGHEDU + TCURTENR +  ALGNCUR + AELNG1 + DPMTEXP + AMOVERS + age + ALEASETP + ACAROWN| 0 |CONTROL, data  = recs_trial_final)

SHOWad1_ <- lfe::felm(home_av ~ APRACE | CONTROL + SEQUENCE.x + month + HCITY + market + ARELATE2 + HHMTYPE + SAPPTAM + TSEX.x + THHEGAI + TPEGAI + THIGHEDU + TCURTENR +  ALGNCUR + AELNG1 + DPMTEXP + AMOVERS + age + ALEASETP + ACAROWN| 0 | CONTROL, data  = recs_trial_final)
SHOWad3_ <- lfe::felm(home_av ~ APRACE + w2012pc_Ad + b2012pc_Ad + a2012pc_Ad + hisp2012pc_Ad + logAdPrice | CONTROL + SEQUENCE.x + month + HCITY + market + ARELATE2 + HHMTYPE + SAPPTAM + TSEX.x + THHEGAI + TPEGAI + THIGHEDU + TCURTENR +  ALGNCUR + AELNG1 + DPMTEXP + AMOVERS + age + ALEASETP + ACAROWN| 0 |CONTROL, data  = recs_trial_final)

### GENERATE TABLES
out <- "tmp/"

###########Control Group Mean####################

stargazer::stargazer(SHOW1, SHOW3, SHOWad1, SHOWad3,
          type = "text",
          out = paste0(out, "HUM_tab5_JPE.txt"),
          title="Steering and Neighborhood Effects",
          model.numbers = F,
          keep = c("ofcolor"),
          covariate.labels = c("Racial Minority"),
          keep.stat=c("n","adj.rsq"),
          digits=4,digits.extra=0,no.space=T,align=T,model.names=F,notes.append=T,object.names=F,
          add.lines = list(c("ln(Price) Advert Home","N","Y","N","Y"),
                           c("Racial Comp Advert Home","N","Y","N","Y")))


stargazer::stargazer(SHOW1_, SHOW3_, SHOWad1_, SHOWad3_,
          type = "text",
          out = paste0(out, "HUM_tab5_JPE_.txt"),
          title="Steering and Neighborhood Effects",
          dep.var.labels.include = F,
          column.labels = c("Number of Recommendations","Home Availability"),
          model.numbers = F,
          keep = c("APRACE"),
          covariate.labels = c("African American",
                               "Hispanic",
                               "Asian",
                               "Other"),
          keep.stat=c("n","adj.rsq"),
          digits=4,digits.extra=0,no.space=T,align=T,model.names=F,notes.append=T,object.names=F,
          add.lines = list(c("ln(Price) Advert Home","N","Y","N","Y"),
                           c("Racial Comp Advert Home","N","Y","N","Y")))



```
